[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-blog_os.json"

# It links the given executable with the project's bootloader dependency and then launches QEMU. 
[target.'cfg(target_os = "none")']
runner = "bootimage runner"
